; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27053.0 

; Generated by VC++ for Common Language Runtime
.file "G:\repogitory\hm_powershell\hmPS.src\hmPS\Debug\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
